import {Poppins} from 'next/font/google'
import './style/general.scss'

const poppins = Poppins({weight: ['300', '400', '500', '600', '700', '800'], subsets: ['latin']})

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({children}: {children: React.ReactNode}) {
	return (
		<html lang='en'>
			<body className={poppins.className}>{children}</body>
		</html>
	)
}
