import HeaderEdit from '@/app/edit/components/HeaderEdit'

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function EditLayout({children}: {children: React.ReactNode}) {
	return (
		<>
			<HeaderEdit />
			{children}
		</>
	)
}
